### ISSUE TITLE
Mahotas 1.4.8 ModuleNotFoundError

### ISSUE THREAD

**Issue by Jhsmit** [luispedro/mahotas#108]
I'm experiencing problems with the 1.4.8 release of Mahotas. 
My appveyor CI used to pass [(logs)](https://ci.appveyor.com/project/Jhsmit/colicoords/builds/27906904) but when i rerun the same build [(logs)](https://ci.appveyor.com/project/Jhsmit/colicoords/builds/28768879) I get the following error:

``ModuleNotFoundError: No module named 'imread'``

Because I dont have any of the dependencies installed. This used to not be a problem, I suspect because the error was caught in the try/except as an ``ImportError``. For some reason, the error is now raised as a ``ModuleNotFoundError``.

``ModuleNotFoundError`` is new in python 3.6 but both runs are build with the same python 3.6.8. When I create a fresh new conda python 3.6 environment locally and install mahotas by ``conda install -c conda-forge mahotas`` I get the same error upon running ``import mahotas``.

**Comment by luispedro** [comment]
Thanks. This was a bug. Fixed on master. I can do a release later (I'm on the wrong computer for that :)

**Comment by Jhsmit** [comment]
Great, all my tests are working again, thanks :)
