### ISSUE TITLE
Can't install package at conda

### ISSUE THREAD

**Issue by Madreyv** [luispedro/mahotas#110]
If I try to install package, it return the following erro:

Package setuptools conflicts for:
mahotas -> python=3.5 -> pip -> setuptools
python=3.7 -> pip -> setuptools
Package certifi conflicts for:
mahotas -> python=3.5 -> pip -> requests -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
Package wincertstore conflicts for:
mahotas -> python=3.5 -> pip -> setuptools -> wincertstore[version='>=0.2']
python=3.7 -> pip -> setuptools -> wincertstore[version='>=0.2']
Package ca-certificates conflicts for:
mahotas -> python=3.5 -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
Package msgpack-python conflicts for:
mahotas -> python=3.5 -> pip -> cachecontrol -> msgpack-python

These are my conda info

     active environment : dados
    active env location : C:\Users\Madreyv\Anaconda3\envs\dados
            shell level : 1
       user config file : C:\Users\Madreyv\.condarc
 populated config files : C:\Users\Madreyv\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\Users\Madreyv\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Madreyv\Anaconda3\pkgs
                          C:\Users\Madreyv\.conda\pkgs
                          C:\Users\Madreyv\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Madreyv\Anaconda3\envs
                          C:\Users\Madreyv\.conda\envs
                          C:\Users\Madreyv\AppData\Local\conda\conda\envs
               platform : win-32

**Comment by luispedro** [comment]
Hi, this is some weird conda issue.

You can try reporting it at:

https://github.com/conda-forge/mahotas-feedstock/
