### ISSUE TITLE
Try installing and then changing to another directory before importing mahotas.

### ISSUE THREAD

**Issue by Algabri** [luispedro/mahotas#113]
/usr/bin/python2.7 /home/redhwan/learn.py
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Could not import submodules (exact error was: numpy.core.multiarray failed to import).

There are many reasons for this error the most common one is that you have
either not built the packages or have built (using `python setup.py build`) or
installed them (using `python setup.py install`) and then proceeded to test
mahotas **without changing the current directory**.

Try installing and then changing to another directory before importing mahotas.

Process finished with exit code 0

I already installed it, you can see it in below. What is wrong?

```
lz4                                0.7.0                  
mahotas                            1.4.9                  
Mako                               1.1.2                  
Markdown                           3.1.1                  
MarkupSafe                         0.23 
```

**Comment by luispedro** [comment]
You have some numpy version mismatch (`RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa`). Probably multiple versions of Numpy installed?

**Comment by luispedro** [comment]
I believe this is an installation error and we are about to start shipping wheels too (#114) so that may be a better way in any case (also, see the conda package https://anaconda.org/conda-forge/mahotas)
