### ISSUE TITLE
Not Able To import mahotas

### ISSUE THREAD

**Issue by nikhilrana015** [luispedro/mahotas#116]
I install mahotas using pip in my virtual env created through conda. When I tried to import it it gives me an error:

Could not import submodules (exact error was: DLL load failed: The specified module could not be found.).

There are many reasons for this error the most common one is that you have
either not built the packages or have built (using `python setup.py build`) or
installed them (using `python setup.py install`) and then proceeded to test
mahotas **without changing the current directory**.

Try installing and then changing to another directory before importing mahotas.

I also get the StackOverflow answer onto this but I am confused about which compiled packages to use. There are soo many.

[https://stackoverflow.com/questions/16226296/error-importing-mahotas-in-python-missing-dll-file](url)

**Comment by luispedro** [comment]
Sorry, these Windows issues are a bit tricky for me to debug as I don't generally use it (or understand anything about it).

Conda-forge should have Windows packages, though: https://anaconda.org/conda-forge/mahotas, if you are already using conda

**Comment by nikhilrana015** [comment]
Thanks, It works.
