### ISSUE TITLE
 Find the the haralick feature name from the value using Mahotas

### ISSUE THREAD

**Issue by Dev-Gaju** [luispedro/mahotas#121]
When I Implemented mahotas for feature extraction by Haralick  I can easily get 4*13 value.  Now the question is which value defines which feature like, which called entropy, correlation, sum variance, and so on. How can I see the by using code?

Like using features[1][1] can take one feature but what is the name of this feature?

**Comment by luispedro** [comment]
The object `haralick_labels` in the texture module has the right answer for you

```python
import mahotas as mh
print(mh.features.texture.haralick_labels[1])
```

The second dimension is the four directions. Normally the mean (or mean + variance) over the four dimensions is used (which in mahotas, you get by passing `return_mean=True` to the `haralick()` function).
