### ISSUE TITLE
freeimage tests fail due to use of `tmpdir`

### ISSUE THREAD

**Issue by risicle** [luispedro/mahotas#129]
Hi,

In building the Nix package for mahotas, we noticed that the tests in `test_freeimage.py` are failing. You're probably not seeing them fail because your CI setup doesn't appear to have freeimage support working so these are being skipped. The failures are of the form:

```
_____________________________ test_save_load_rgba ______________________________

tmpdir = local('/private/tmp/nix-build-python3.8-mahotas-1.4.11.drv-0/pytest-of-_nixbld2/pytest-0/test_save_load_rgba0')

    def test_save_load_rgba(tmpdir):
        fname = tmpdir.join('mahotas_test.png')
        img = np.arange(256).reshape((8,8,4)).astype(np.uint8)
>       freeimage.imsave(fname, img)

mahotas/tests/test_freeimage.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mahotas/io/freeimage.py:798: in imsave
    write(img, filename)
mahotas/io/freeimage.py:581: in write
    filename = _bytestr(filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = local('/private/tmp/nix-build-python3.8-mahotas-1.4.11.drv-0/pytest-of-_nixbld2/pytest-0/test_save_load_rgba0/mahotas_test.png')

>   _bytestr = lambda x: x.encode(_encoding)
E   AttributeError: 'LocalPath' object has no attribute 'encode'

mahotas/io/freeimage.py:806: AttributeError
```

The problem arises from the use of `tmpdir`-based paths, which are `py.local` objects (https://py.readthedocs.io/en/latest/path.html). These do not have `.encode()` methods (at least those I've tested from `py-1.10.0` don't). Either the tests should stringify these paths before passing them to mahotas or mahotas should be ensuring these are stringified before attempting to `.encode()` them. The latter is probably better as it would result in mahotas being more robust to inputs.

A complete build log for 1.4.11 on macos is available at https://hydra.nixos.org/log/mi2r0wsg9zkd1k9lmgkw1fv9rcy5i36i-python3.8-mahotas-1.4.11.drv (I understand the final failure seen there is already fixed in the latest release).

**Comment by luispedro** [comment]
Thanks! This is a good catch. I will first fix testing to make sure it gets picked up  in the future too. Then, I will fix the underlying issue
