### ISSUE TITLE
Online documentation outdated

### ISSUE THREAD

**Issue by stefanv** [luispedro/mahotas#140]
It looks like the documentation at https://mahotas.readthedocs.io/en/latest/ does not match what is included in the repository:

- https://mahotas.readthedocs.io/en/latest/history.html
- https://github.com/luispedro/mahotas/blob/master/docs/source/history.rst

Would it be possible to publish the new version?

**Comment by luispedro** [comment]
Thanks. This should update in a few minutes

**Comment by stefanv** [comment]
Thank you! I was updating the SciPy Lecture notes and we point to Mahotas as one of the image processing libraries in the ecosystem. 🙏
