### ISSUE TITLE
How to return classification? After training the model

### ISSUE THREAD

**Issue by sleepingcat4** [luispedro/mahotas#145]
I've recently trained a model on my images to label unlabelled data in my dataset using mahotas. But, I don't know how to receive the results. Can someone help me a bit?

https://mahotas.readthedocs.io/en/latest/classification.html

Code to get the class results

```
for data_point, classification in zip(unlabeled, labeled):
    print("Data Point:", data_point)
    print("Classification:", classification)
```

**Comment by luispedro** [comment]
Hi. I cannot immediately see what you are doing wrong, but this is not really a `mahotas` question/issue, so I am going to close here.

**Comment by sleepingcat4** [comment]
the tutorial of Mahotas does not show how someone can return the predicted class after labelling the **unlabeled** data. 

I was asking help in that spectrum, your help will helpful.
