### ISSUE TITLE
`std::random_shuffle` deprecated in C++14 and removed in C++17

### ISSUE THREAD

**Issue by jakirkham** [luispedro/mahotas#146]
In building mahotas, came across the following build error

```cpp
mahotas/_morph.cpp:864:10: error: no member named 'random_shuffle' in namespace 'std'
    std::random_shuffle(neighbours.begin(), neighbours.end());
    ~~~~~^
In file included from mahotas/_morph.cpp:13:
```

It traces back to this line:

https://github.com/luispedro/mahotas/blob/ff58c8e056a96621b724a505d7c235b11c70fe67/mahotas/_morph.cpp#L864

<hr>

It appears C++ has deprecated `std::random_shuffle` in C+14 and removed it in C++17 based on [N3775]( https://isocpp.org/files/papers/N3775.pdf ). Here's a quote from that accepted proposal:

> The rationale for deprecating `random_shuffle()` is that one overload is specified so as to depend on `rand`, while the other overload is specified so as to require a hard-to-produce distribution object from the user; such a distribution is already an implicit part of `shuffle`, which we retain.

**Comment by luispedro** [comment]
Thanks for the report.

I can do a new release soon, but I am not on the right laptop for it rn

**Comment by jakirkham** [comment]
No worries. Tbh am pleasantly surprised this was fixed so quickly. Thank you! 🙏

Think we can apply it as a patch, which is good enough for now

**Comment by luispedro** [comment]
Version 1.4.14 has now been released on PyPI and here, including this patch

**Comment by jakirkham** [comment]
Thanks Luis! 🙏

Removed the patch and updated in PR: https://github.com/conda-forge/mahotas-feedstock/pull/48
