### ISSUE TITLE
Novice mahotas user: unknown error

### ISSUE THREAD

**Issue by duytrung** [luispedro/mahotas#55]
Hi, 

I'm new to python and mahotas, I downloaded and installed the program. However, when running the samples in mahotas docs, I encountered errors, and tried to run the test and here is the results:

In [14]: mahotas.test()
...................................................................................-------------------------------------
--------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\Pyx\lib\site-packages\mahotas\_ctypes\callbacks.c in 'calling callback function'()

C:\Pyx\lib\site-packages\mahotas\io\freeimage.py in _error_handler(fif, message)
    222 @_functype(None, ctypes.c_int, ctypes.c_char_p)
    223 def _error_handler(fif, message):
--> 224     raise RuntimeError('mahotas.freeimage: FreeImage error: %s' % message)
    225
    226 _FI.FreeImage_SetOutputMessage(_error_handler)

RuntimeError: mahotas.freeimage: FreeImage error: FreeImage_Save: failed to open file /tmp/mahotas_test.png
E---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\Pyx\lib\site-packages\mahotas\_ctypes\callbacks.c in 'calling callback function'()

C:\Pyx\lib\site-packages\mahotas\io\freeimage.py in _error_handler(fif, message)
    222 @_functype(None, ctypes.c_int, ctypes.c_char_p)
    223 def _error_handler(fif, message):
--> 224     raise RuntimeError('mahotas.freeimage: FreeImage error: %s' % message)
    225
    226 _FI.FreeImage_SetOutputMessage(_error_handler)

RuntimeError: mahotas.freeimage: FreeImage error: FreeImage_Save: failed to open file /tmp/mahotas_test.png
E.---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\Pyx\lib\site-packages\mahotas\_ctypes\callbacks.c in 'calling callback function'()

C:\Pyx\lib\site-packages\mahotas\io\freeimage.py in _error_handler(fif, message)
    222 @_functype(None, ctypes.c_int, ctypes.c_char_p)
    223 def _error_handler(fif, message):
--> 224     raise RuntimeError('mahotas.freeimage: FreeImage error: %s' % message)
    225
    226 _FI.FreeImage_SetOutputMessage(_error_handler)

RuntimeError: mahotas.freeimage: FreeImage error: FreeImage_Save: failed to open file /tmp/mahotas_test.png
E..---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\Pyx\lib\site-packages\mahotas\_ctypes\callbacks.c in 'calling callback function'()

C:\Pyx\lib\site-packages\mahotas\io\freeimage.py in _error_handler(fif, message)
    222 @_functype(None, ctypes.c_int, ctypes.c_char_p)
    223 def _error_handler(fif, message):
--> 224     raise RuntimeError('mahotas.freeimage: FreeImage error: %s' % message)
    225
    226 _FI.FreeImage_SetOutputMessage(_error_handler)

RuntimeError: mahotas.freeimage: FreeImage error: Failed to open /tmp/mahotas_test.fispool, No such file or directory
E---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
C:\Pyx\lib\site-packages\mahotas\_ctypes\callbacks.c in 'calling callback function'()

C:\Pyx\lib\site-packages\mahotas\io\freeimage.py in _error_handler(fif, message)
    222 @_functype(None, ctypes.c_int, ctypes.c_char_p)
    223 def _error_handler(fif, message):
--> 224     raise RuntimeError('mahotas.freeimage: FreeImage error: %s' % message)
    225
    226 _FI.FreeImage_SetOutputMessage(_error_handler)

RuntimeError: mahotas.freeimage: FreeImage error: FreeImage_Save: failed to open file /tmp/mahotas_test.png
E...................................................................F...................................................
...................................................................................E..........
======================================================================
ERROR: mahotas.tests.test_freeimage.test_freeimage
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_freeimage.py", line 25, in test_freeimage
    freeimage.imsave(_testimgname, img)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 798, in imsave
    write(img, filename)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 597, in write
    res = _FI.FreeImage_Save(ftype, bitmap, filename, flags)
WindowsError: exception: priviledged instruction

======================================================================
ERROR: mahotas.tests.test_freeimage.test_as_grey
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_freeimage.py", line 34, in test_as_grey
    freeimage.imsave(_testimgname, colour.astype(np.uint8))
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 798, in imsave
    write(img, filename)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 597, in write
    res = _FI.FreeImage_Save(ftype, bitmap, filename, flags)
WindowsError: exception: priviledged instruction

======================================================================
ERROR: mahotas.tests.test_freeimage.test_save_load_rgba
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_freeimage.py", line 51, in test_save_load_rgba
    freeimage.imsave(_testimgname, img)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 798, in imsave
    write(img, filename)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 597, in write
    res = _FI.FreeImage_Save(ftype, bitmap, filename, flags)
WindowsError: exception: priviledged instruction

======================================================================
ERROR: mahotas.tests.test_freeimage.test_multi
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_freeimage.py", line 83, in test_multi
    freeimage.write_multipage(fs, _testtif)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 630, in write_multipage
    _FI.FreeImage_CloseMultiBitmap(multibitmap, flags)
WindowsError: exception: access violation reading 0x00000066

======================================================================
ERROR: mahotas.tests.test_freeimage.test_uint16
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_freeimage.py", line 92, in test_uint16
    freeimage.imsave(_testimgname, img)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 798, in imsave
    write(img, filename)
  File "C:\Pyx\lib\site-packages\mahotas\io\freeimage.py", line 597, in write
    res = _FI.FreeImage_Save(ftype, bitmap, filename, flags)
WindowsError: exception: priviledged instruction

======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'float128')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\loader.py", line 251, in generate
    for test in g():
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_watershed.py", line 39, in test_watershed
    np.float32, np.float64, np.float128, float]:
AttributeError: 'module' object has no attribute 'float128'

======================================================================
FAIL: mahotas.tests.test_io.test_pil
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Pyx\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_io.py", line 27, in execute
    test(*args, **kwargs)
  File "C:\Pyx\lib\site-packages\mahotas\tests\test_io.py", line 69, in test_pil
    assert np.all( pil.imread(filename) == lena )
AssertionError

----------------------------------------------------------------------
Ran 304 tests in 221.107s

FAILED (errors=6, failures=1)

In [15]:_

How can I send the detail debug, include related files?

Thanks

**Comment by luispedro** [comment]
Thank you for your report. My first impression is that this is because the test suite assumes a Unix system (with a /tmp directory, for example), so it fails on Windows. Does the rest of the package generally work?

Luis

**Comment by luispedro** [comment]
I think the issues that I could identify are fixed (the `float128` error has also been fixed in a newer version by another patch).

Please provide more details if you wish to reopen.
