### ISSUE TITLE
[Inquery] Change distance in Haralick features

### ISSUE THREAD

**Issue by glemaitre** [luispedro/mahotas#60]
Hi,

I am currently working with Haralick features and wanted to have a discussion about that.
Sometimes, it could be handy to play with a distance parameter when computing the co-occurence instead of using the default value (1 px).

I was checking what could be the best way to modify the source and thought that it could be easier to discuss here. I see two possibilities:
* Modifying the distance for the variable _2d_deltas and _3d_deltas with an initialisation. However, I do not have a clear idea of the consequences (I did not go into detail in the C file which allow to compute the GLCM)
* Resample the input image. But again, I am not really sure of the consistency.

Cheers,
--
Guillaume Lemaitre

**Comment by luispedro** [comment]
The resampling is the easiest and can be done with the existing code, but it is not the exact same result.

You don't need to change the C code, you just need to pass it a correct "neighborhood", for example for D=2, direction "right", instead of

    [[0 0 0]
     [0 0 1]
     [0 0 0]]

you need to pass it:

    [[0 0 0 0]
     [0 0 0 1]
     [0 0 0 0]]

HTH
Luis

**Comment by glemaitre** [comment]
thanks

**Comment by luispedro** [comment]
Actually, that probably should be:

    [[0 0 0 0 0]
     [0 0 0 0 1]
     [0 0 0 0 0]]

(ie, a 5x5 matrix).

**Comment by glemaitre** [comment]
Ok if I come to do it, I would make a pull request if you are interested.

**Comment by luispedro** [comment]
Thanks. I would certainly be happy to see this feature (I use the downsampling method myself, but others have asked about it).
