### ISSUE TITLE
mh.labeled.bbox strange behavior

### ISSUE THREAD

**Issue by haehn** [luispedro/mahotas#61]
I encounter the following strange behavior where mh.labeled.bbox is all zeros:
```
aaa = array([[[2256,  402,  402],
        [2256,  402,  402],
        [2256,  402,  402]],

       [[2256,  402,  402],
        [2256,  402,  402],
        [2256,  402,  402]],

       [[2256,  402,  402],
        [2256,  402,  402],
        [2256,  402,  402]]], dtype=uint32)

mh.labeled.bbox(aaa)
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ..., 
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

mh.labeled.bbox(aaa).shape
(2257, 6)

mh.bbox(aaa==2256) # but this works
array([0, 3, 0, 3, 0, 1])
```

**Comment by luispedro** [comment]
Fixed on github now (and will be in the next release), thank you for the report.

**Comment by haehn** [comment]
thank you! what was the problem (just out of curiosity)?

**Comment by luispedro** [comment]
> thank you! what was the problem (just out of curiosity)?


There is a check for empty regions (which return all 0 coordinates), but
(probably because the code had been adapted from the binary bbox code)
it only checked for the first region. If that was empty, then it would
return all 0s.

The correct thing is to check each region separately.

HTH Luis
