### ISSUE TITLE
overlay() doesn't return expected result

### ISSUE THREAD

**Issue by HackerMD** [luispedro/mahotas#62]
Following this [tutorial](http://pythonvision.org/basic-tutorial/#finding-the-seeds) I tried the overlay() function on one of my images (DAPI stain):

```{python}
import mahotas as mh
import numpy as np
from matplotlib import pyplot as plt  # also tried: import pylab as plt

filename = ''  # some image file
img = mh.imread(filename)

thresh = mh.otsu(img.astype(np.uint))
img_bin = img > thresh

img_over = mh.overlay(img, red=img_bin)

plt.imshow(img_over)
plt.show()
```

This results in a gray image without any coloring.

```{python}
(img_over[:,:,0] == img_over[:,:,1]).all()
```

returns `True`

I'm using *mahotas* version 1.4 and *matplotlib* version 1.4.3 and *python* 2.7

**Comment by luispedro** [comment]
Sorry, I cannot reproduce. Do you still have this error if, instead of loading an image from disk (which I cannot use unless you upload it), you use

   img = mh.demos.load('nuclear', as_grey=True)

**Comment by HackerMD** [comment]
Thanks for looking into it! Using your demo works! However, the color is not red, but cyan.

When I read my image file as follows

```{python}
img = mh.imread(filename).astype(np.uint8).astype(np.float64)
```

to get the same data type and scale as the loaded demo image, I get a colored image, but again the color is cyan instead of red. In addition, the the grayscale image (first input argument) is colorized and not the binary mask (second input argument).

**Comment by luispedro** [comment]
Ah! OK, I see the cyan now.

This is partially a matplotlib issue: ``imshow`` does not support 16 bit images. See:

https://github.com/matplotlib/matplotlib/issues/2499
https://github.com/matplotlib/matplotlib/pull/2632

Maybe ``overlay()`` should convert its arguments to ``np.uint8``. But the real issue, IMHO, is matplotlib's obtuseness.
