### ISSUE TITLE
Not (correctly) pip installable

### ISSUE THREAD

**Issue by ctheune** [luispedro/mahotas#68]
Hi,

you're importing numpy in setup.py. This causes automatic dependency resolution to fail and one has to manually install numpy. This conflicts with anything that is smarter than a shell script automating installation.

Would you mind making mahtos cleanly install in a fresh virtualenv when calling bin/pip install?

**Comment by luispedro** [comment]
I'm more than willing to accept a patch, I'm not too sure how to do this cleanly myself: I need to call the function ``numpy.get_includes()`` in order to get the right include paths.

**Comment by fish2000** [comment]
You can always do a fallback sort of thing like e.g.:

```python
try:
    import numpy
except ImportError:
    class FakeNumpy(object):
        def get_includes(self):
            # use a saner default here
            return "."
    numpy = FakeNumpy()
```
… I use pretty much this exact snippet to avoid this `setup.py` dependency enigma, myself.

**Comment by luispedro** [comment]
Thanks @fish2000 , I will implement it that way.

Does this mean that pip will import/run `setup.py` twice? A first time just to get the dependencies and a second time once the dependencies are installed?

**Comment by fish2000** [comment]
Hey no problem, glad I could help mahotas, which is excellent!

As far as I can ascertain, pip can end up both parsing `setup.py` and running it – this can happen a number of times times and it can vary depending on build flags and settings, as well as other esoteric factors e.g. if (say) you’re using the `wheel` extension.

Personally I would say that I know enough to be dangerous, regarding Pip – like most Python extension authors I have had to add all sorts of build-related code to `setup.py` files. Testing these is always tricky but travis-ci is very helpful, indeed!
