### ISSUE TITLE
Convolution: weights with integer data type

### ISSUE THREAD

**Issue by HackerMD** [luispedro/mahotas#75]
I'm using `mahotas.convolve` to detect edges in an image with a `Sobel` filter:

```python
f = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]], dtype=float)
sobel_h = mh.convolve(image.astype(float), f)
sobel_v = mh.convolve(image.astype(float), f.T)
gradient = np.abs(sobel_v) + np.abs(sobel_h)
```

This works fine when `image` and weights `f` are both cast to type `float` and gives the same results as MATLAB's `imfilter`:

```matlab
f = fspecial('sobel');
sobel_h = imfilter(image, f);
sobel_v = imfilter(image, f');
edges = abs(sobel_h) + abs(sobel_v);
```

![screen shot 2016-07-12 at 16 33 16](https://cloud.githubusercontent.com/assets/6855297/16771109/9da4fe8a-484f-11e6-944c-c7c80f85621d.png)

However, when using unsigned integer type (same type as `image`, which has type `numpy.uint16`!) the output is different.

```python
f = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
sobel_h = mh.convolve(image, f)
sobel_v = mh.convolve(image, f.T)
edges = np.abs(sobel_v) + np.abs(sobel_h)
```

![screen shot 2016-07-12 at 16 31 00](https://cloud.githubusercontent.com/assets/6855297/16771126/ad60a4be-484f-11e6-8824-ea02a0555db3.png)

**Comment by luispedro** [comment]
Yeah, this isn't the best result. The ``convolve`` function always returns in the same type as its input. Unfortunately this means that negative numbers get converted to high positive ones when you pass it an unsigned type.

For backwards compatibility reasons, I am wary of changing it.

**Comment by HackerMD** [comment]
Fair enough! It's also clearly stated in the docs. But maybe adding an additional warning in the docs that this can lead to "unexpected" results when passing arrays with unsigned integer data types.
