### ISSUE TITLE
pip install gives error -> Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by angeleah** [luispedro/mahotas#79]
I did a fresh install on my computer and I'm getting setup for CV again. When I use pip to install, I am getting the error below. I am newer to python, so apologies if it is something obvious but help would be greatly appreciated!

pip install mahotas
Collecting mahotas
  Using cached mahotas-1.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
…/mahotas/setup.py", line 50, in <module>
        long_description = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1

**Comment by luispedro** [comment]
This was a packaging mistake. I just fixed it and release version 1.4.3.

Sorry

**Comment by angeleah** [comment]
No problem. Thank you for your speedy fix!
