### ISSUE TITLE
Bug in haralick_features

### ISSUE THREAD

**Issue by mchandak29** [luispedro/mahotas#94]
There is a bug in the function haralick_features in https://github.com/luispedro/mahotas/blob/master/mahotas/features/texture.py . 
when the variable 'use_x_minus_y_variance' is false(default), it is calculating  ``VAR[|x-y|]`` instead of ``VAR[P(|x-y|)]`` .

**Comment by luispedro** [comment]
see #36

The default is `VAR( P(|x-y|) )`, actually. I find the argument that it should be `VAR(|x-y|)` somewhat persuasive, but for backwards compat, I kept this as the default.

**Comment by mchandak29** [comment]
`        if use_x_minus_y_variance:
            mu_x_minus_y = np.dot(px_minus_y, k)
            mu_x_minus_y_sq = np.dot(px_minus_y, k2)
            feats[ 9] = mu_x_minus_y_sq - mu_x_minus_y**2
        else:
            feats[ 9] = px_minus_y.var()`

This is the code snippet of features.py where you're computing feats[9] as VAR( P(|x-y|) ) when use_x_minus_y_variance is TRUE but the default is FALSE .
just have a look!

**Comment by luispedro** [comment]
I still don't understand this. When `use_x_minus_y_variance` is true, the code is

            mu_x_minus_y = np.dot(px_minus_y, k)
            mu_x_minus_y_sq = np.dot(px_minus_y, k2)
            feats[ 9] = mu_x_minus_y_sq - mu_x_minus_y**2

which is `VAR(|x-y|)`. When, it's false, then it's simpler:

            feats[ 9] = px_minus_y.var()

which is `Var( P(|x-y|) )`.
