### ISSUE TITLE
Mr  luispedro :+1: May I push my code about Hough transforms  using in detect line in a image ?   Can you interview my code?  Thank you again!

### ISSUE THREAD

**Issue by jasson2001** [luispedro/mahotas#98]
Frist , thank you for your excellent work!  I am very glad to join your project!
   Recently, I help a kindly friend to do some thing- Hough transforms ,  using in detect line in a image, 
Could I pull my code? Can you interview my code? 
Thank you again!

_Originally posted by @jasson2001 in https://github.com/luispedro/mahotas/issues/85#issuecomment-426209909_

**Comment by luispedro** [comment]
Closing in favour of #99
